### ISSUE TITLE
error after :   ionic plugin add https://github.com/driftyco/ionic-plugins-deploy

### ISSUE THREAD

**Issue by antonyfrance** [driftyco/ionic-plugin-deploy#29]
Hi, 

i try to do : Deploy From Scratch. but unfortunately, I have found this problem :

Updated the hooks directory to have execute permissions
Fetching plugin "https://github.com/driftyco/ionic-plugins-deploy" via git clone
Saving plugin to package.json file
Error happened { [Error: Cannot find module 'C:\Users\MAREUIL\ionic\test_MAJ_app\deploy-tutorial\plu
gins\fetch.json'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'C:\Users\MAREUIL\ionic\test_MAJ_app\deploy-tutorial\plugins\fetch.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.getPluginFromFetchJsonByLocator (C:\Users\MAREUIL\AppData\Roaming\npm\node_modules\ion
ic\node_modules\ionic-app-lib\lib\state.js:673:19)
    at Object.savePlugin (C:\Users\MAREUIL\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic
-app-lib\lib\state.js:622:36)
    at C:\Users\MAREUIL\AppData\Roaming\npm\node_modules\ionic\lib\ionic\cordova.js:90:22
    at _fulfilled (C:\Users\MAREUIL\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:5
4)
    at self.promiseDispatch.done (C:\Users\MAREUIL\AppData\Roaming\npm\node_modules\ionic\node_modul
es\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\MAREUIL\AppData\Roaming\npm\node_modules\ionic\node
_modules\q\q.js:749:13)
    at C:\Users\MAREUIL\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:557:44
    at flush (C:\Users\MAREUIL\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:355:11)

In  this system information:

Cordova CLI: 4.2.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Windows 8.1
Node Version: v0.12.7

best regards

**Comment by ericb** [comment]
Are you able to install other plugins, or are you only getting the error on this specific plugin?

**Comment by antonyfrance** [comment]
Hi,

I have this only  for this specific plugin.

but i have not upgraded  cordova to 5.X
http://docs.ionic.io/docs/deploy-install
....

Regards

**Comment by ericb** [comment]
@antonyfrance Has this been resolved?

**Comment by antonyfrance** [comment]
Yes
