### ISSUE TITLE
deploy app crash log

### ISSUE THREAD

**Issue by zhaoxinpeng** [driftyco/ionic-plugin-deploy#57]
hi.
when i use deploy.update() to updata my app.my app crash,the err log is
java.lang.SecurityException: JPushSA.onResume(Context) must be invoked in Activity.onResume()
	at cn.jpush.android.api.e.c(Unknown Source)
	at cn.jpush.android.api.e.b(Unknown Source)
	at cn.jpush.android.api.JPushInterface.onPause(Unknown Source)
	at cn.jpush.phonegap.JPushPlugin.onPause(JPushPlugin.java:110)
	at org.apache.cordova.PluginManager.onPause(PluginManager.java:209)
	at org.apache.cordova.PluginManager.init(PluginManager.java:81)
	at org.apache.cordova.CordovaWebViewImpl.loadUrlIntoView(CordovaWebViewImpl.java:138)
	at io.ionic.deploy.IonicDeploy$5.run(IonicDeploy.java:711)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5432)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)

why?who can help me ,thanks

**Comment by ericb** [comment]
This appears to be caused by another plugin you have installed (JPushSA). Does that seem familiar to you?

**Comment by zhaoxinpeng** [comment]
thank you,i change the JPushsa plugin ,now it works fine.
